switch to Flask-Reuploaded==0.3.2
Fix ImportError: cannot import name 'secure_filename'

appears to be now maintained by https://pypi.org/project/Flask-Reuploaded/ jugmac00